<h1 align=center style="line-height:200%;font-family:vazir;color:#0099cc">
<font face="vazirmatn" color="#0099cc">
پیشنهاد خودکار
</font>
</h1>

<h2 align=right style="line-height:200%;font-family:vazir;color:#0099cc">
<font face="vazirmatn" color="#0099cc">
مقدمه و صورت مسئله
</font>
</h2>

<p dir=rtl style="direction: rtl; text-align: justify; line-height:200%; font-family:vazir; font-size:medium">
<font face="vazirmatn" size=3>
    به یک تمرین جالب و کاربردی از پردازش زبان طبیعی (NLP) خوش آمدید!  در این تمرین به سراغ یک مسئله‌ی کاملاً واقعی و چالش‌برانگیز صنعت خواهیم رفت.
    مشاهده کرده‌اید که در وب‌سایت‌ها هنگامی‌که در حال تایپ داخل یک فیلد متنی هستید معمولاً لیستی از متن‌های مشابه به شما پیشنهاد می‌شود. نمونه‌ای از این قابلیت که در وب سایت <a href="https://mrbilit.com/bus-ticket" target="_blank">مستربلیط</a> به کار گرفته شده را در تصویر زیر مشاهده می‌کنید. 
</font>
</p>


<center>
<img src="screenshot.png">
</center>

<p dir=rtl style="direction: rtl; text-align: justify; line-height:200%; font-family:vazir; font-size:medium">
<font face="vazirmatn" size=3>
    با این حال معمولاً چنین لیست‌های پیشنهادی‌ای بسیار ساده هستند و تنها عباراتی را که با رشته‌ی تایپ‌شده‌ی کاربر شروع می‌شوند پیشنهاد می‌دهند تا کاربر نیازی به تکمیل تایپ خود نداشته باشد و زودتر به نتیجه برسد. اما در این تمرین قصد داریم پیشنهاددهنده‌ای بسازیم که هوشمندتر و منعطف‌تر عمل کند. به‌عنوان مثال شاید کاربر عبارت «بابل» را تایپ کرده اما در ابتدا غلط املایی داشته و منظورش «زابل» بوده باشد.  یا شاید همان‌طور که حتماً برای شما هم پیش آمده و روی اعصاب‌تان رفته یادش رفته باشد که کیبورد خود را روی زبان فارسی تنظیم کند و عبارتی مثل «fhfg» را تایپ کرده باشد. همچنین چرا اسم‌های انگلیسی شهرها را هم در نظر نگیریم و وقتی شخص مثلاً «Zahedan» را تایپ کرده باشد متوجه نشویم که منظورش «<span style="color: red"}>زاهدان</span>» بوده است؟
    با این حال، این‌ها تنها تعدادی از الگوهای ممکن هستند که منجر به بهبود پیشنهادهای سیستم خواهند شد. ما می‌توانیم به کمک داده‌های جمع‌آوری‌شده از آن‌چه که کاربران مرحله به مرحله تایپ کرده‌اند و آن‌چه که در نهایت انتخاب کرده‌اند مدلی طراحی کنیم که با توجه به ورودی کاربر، لیستی از محتمل‌ترین انتخاب‌ها را به وی پیشنهاد دهد.
</font>
</p>

<h2 align=right style="line-height:200%;font-family:vazir;color:#0099cc">
<font face="vazirmatn" color="#0099cc">
وارد کردن کتابخانه‌های مورد نیاز
</font>
</h2>

<p dir=rtl style="direction: rtl; text-align: justify; line-height:200%; font-family:vazir; font-size:medium">
<font face="vazirmatn" size=3>
    ابتدا کتابخانه‌های مورد نیازتان را وارد کنید.
</font>
</p>

In [28]:
import numpy as np
import pandas as pd

<h2 align=right style="line-height:200%;font-family:vazir;color:#0099cc">
<font face="vazirmatn" color="#0099cc">
معرفی مجموعه داده
</font>
</h2>

<p dir=rtl style="direction: rtl; text-align: justify; line-height:200%; font-family:vazir; font-size:medium">
<font face="vazirmatn" size=3>
    هر نمونه‌ی آموزشی از این مجموعه‌داده که در فایل <code dir=ltr>mrbilit_search.json</code> ذخیره شده مربوط به یک مرتبه جست‌و‌جوی کاربر در فیلد متنی است و با ویژگی‌هایی که در جدول زیر شرح داده شده همراه است.
</font>
</p>
<center>
<div dir=rtl style="direction: rtl;line-height:200%;font-family:vazir;font-size:medium">
<font face="vazirmatn" size=3>
    
|ستون|توضیحات|
|:------:|:---:|
|<code>ServiceType</code>|نوع سرویس|
|<code>TypedStrings</code>|لیستی از رشته‌ی تایپ‌شده‌ی کاربر به ترتیب زمانی|
|<code>AcceptString</code>|رشته‌ای که در نهایت انتخاب شده است|

</font>
</div>
</center>

<p dir=rtl style="direction: rtl; text-align: justify; line-height:200%; font-family:vazir; font-size:medium">
<font face="vazirmatn" size=3 color=red>
    <b>نکته:</b>
</font>
<font face="vazirmatn" size=3>
    در این تمرین فقط جست‌و‌جوهای مرتبط با سرویس‌های حمل‌و‌نقل زمینی را در نظر خواهیم گرفت. بنابراین با توجه به ستون <code>ServiceType</code> تنها نمونه‌های سرویس <b>تاکسی</b> و <b>اتوبوس</b> را نگه دارید.
</font>
</p>

<p dir=rtl style="direction: rtl; text-align: justify; line-height:200%; font-family:vazir; font-size:medium">
<font face="vazirmatn" size=3>
    مجموعه‌ی آزمون نیز در فایل <code dir=ltr>test_data.json</code> ذخیره شده و شامل تنها یک ستون به شرح زیر است. به ازای هرکدام از نمونه‌های آزمون باید لیستی از شهرها را پیشنهاد دهید. 
</font>
</p>
<center>
<div dir=rtl style="direction: rtl;line-height:200%;font-family:vazir;font-size:medium">
<font face="vazirmatn" size=3>
    
|ستون|توضیحات|
|:------:|:---:|
|<code>Typed</code>|یک رشته‌ی تایپ‌شده توسط کاربر|

</font>
</div>
</center>

<p dir=rtl style="direction: rtl; text-align: justify; line-height:200%; font-family:vazir; font-size:medium">
<font face="vazirmatn" size=3>
    جهت راحتی شما در دسترسی به نام انگلیسی شهرها مجموعه‌داده‌ای از لیست شهرهای ایران همراه با برخی اطلاعات مهم‌شان جمع‌آوری شده و در فایلی با نام <code>iran_cities.csv</code> قرار گرفته است. این مجموعه‌داده‌ هرچند ناکامل است اما اکثر شهرهای مورد جست‌و‌جو را پوشش می‌دهد. 
</font>
</p>

<p dir=rtl style="direction: rtl; text-align: justify; line-height:200%; font-family:vazir; font-size:medium">
<font face="vazirmatn" size=3>
    علاوه بر این جهت تشخیص اشتباه تایپی به دلیل فعال‌بودن زبان انگلیسی صفحه‌کلید، فایلی با نام <code>typo_char.csv</code> در اختیارتان قرار گرفته که شامل حروف انگلیسی و حروف فارسی متناظر با آن در یک لایه‌ی رایج صفحه‌کلید است.
</font>
</p>

<h2 align=right style="line-height:200%;font-family:vazir;color:#0099cc">
<font face="vazirmatn" color="#0099cc">
خواندن مجموعه داده
</font>
</h2>

<p dir=rtl style="direction: rtl; text-align: justify; line-height:200%; font-family:vazir; font-size:medium">
<font face="vazirmatn" size=3>
    در ابتدا می‌توانید فایل‌های مجموعه‌داده‌ها را بخوانید. لازم به ذکر است برای خواندن فایل‌های <code>json</code> به شکل یک دیتافریم <code>pandas</code> می‌توانید از تابع <code dir=ltr>read_json()</code> استفاده کنید.
</font>
</p>

In [29]:
data = pd.read_json('../data/mrbilit_search.json')
data

,ServiceType,TypedStrings,AcceptString
0,flight,"[, ف, فل, فلو]",فلورانس
1,hotel,"[, H, H,, H, , آ, آو, آوا, آواپ, آواپل, آواپلا...",شیراز
2,hotel,"[, آ, آو, آوا, آواپ, آواپل, آواپلا, آواپلاس]",آواپلاس
3,hotel,[],بین المللی اسپیناس خلیج فارس
4,bus,[],تهران
...,...,...,...
66190,bus,[تهران],تهران
66191,bus,"[ک, کر]",کرمانشاه
66192,hotel,[محمودآباد],محمودآباد
66193,bus,"[, ب, با, باب, بابل]",بابل
66194,bus,[],اصفهان - پایانه صفه

In [30]:
test_data = pd.read_json('../data/test_data.json')
test_data

          Typed
0           تهد
1           نها
2          ساوه
3            یا
4    بندر انزلی
..          ...
514          یز
515          ;v
516         بوک
517        دارا
518       ابادا

[519 rows x 1 columns]

In [31]:
iran_cities = pd.read_csv('../data/iran_cities.csv')
iran_cities

,City EN,City FA,Province,Countise,District,Latitude,Longitude,Area,Elevation,2016 Census,2011 Census,Wikipedia EN,Wikipedia FA,GeoHack
0,Ab Bar,آب‌بر,زنجان,طارم,مرکزی,36.918100,48.964700,709.0,NaN,8091.0,6725.0,https://en.wikipedia.org/wiki/Ab_Bar,https://fa.wikipedia.org/wiki/%D8%A2%D8%A8%E2%...,https://geohack.toolforge.org/geohack.php?lang...
1,Ab Pakhsh,آب‌پخش,بوشهر,دشتستان,آب‌پخش,29.363706,51.070180,251204.0,7003.0,18913.0,17238.0,https://en.wikipedia.org/wiki/Ab_Pakhsh,https://fa.wikipedia.org/wiki/%D8%A2%D8%A8%E2%...,https://geohack.toolforge.org/geohack.php?lang...
2,Abad,آباد,بوشهر,تنگستان,مرکزی,29.028300,51.249100,45.0,NaN,3787.0,3787.0,"https://en.wikipedia.org/wiki/Abad,_Bushehr",https://fa.wikipedia.org/wiki/%D8%A2%D8%A8%D8%...,https://geohack.toolforge.org/geohack.php?lang...
3,Abadan,آبادان,خوزستان,آبادان,مرکزی,30.339167,48.304167,3.0,NaN,231476.0,212744.0,"https://en.wikipedia.org/wiki/Abadan,_Iran",https://fa.wikipedia.org/wiki/%D8%A2%D8%A8%D8%...,https://geohack.toolforge.org/geohack.php?lang...
4,Abadeh,آباده,فارس,آباده,مرکزی,31.180000,52.670000,1890.0,NaN,59116.0,55758.0,https://en.wikipedia.org/wiki/Abadeh,https://fa.wikipedia.org/wiki/%D8%A2%D8%A8%D8%...,https://geohack.toolforge.org/geohack.php?lang...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1251,Zibashahr,زیباشهر,اصفهان,مبارکه,گرکن جنوبی,32.384700,51.567500,1665.0,NaN,10200.0,9668.0,https://en.wikipedia.org/wiki/Zibashahr,https://fa.wikipedia.org/wiki/%D8%B2%DB%8C%D8%...,https://geohack.toolforge.org/geohack.php?lang...
1252,Zirab,زیرآب,مازندران,سوادکوه,زیرآب,36.050000,52.550000,418.0,NaN,16191.0,15679.0,https://en.wikipedia.org/wiki/Zirab,https://fa.wikipedia.org/wiki/%D8%B2%DB%8C%D8%...,https://geohack.toolforge.org/geohack.php?lang...
1253,Zohan,زهان,خراسان جنوبی,زیرکوه,زهان,33.418369,59.814381,NaN,NaN,1118.0,1419.0,https://en.wikipedia.org/wiki/Zohan,https://fa.wikipedia.org/wiki/%D8%B2%D9%87%D8%...,https://geohack.toolforge.org/geohack.php?lang...
1254,Zonuz,زنوز,آذربایجان شرقی,مرند,مرکزی,38.589742,45.828970,1700.0,NaN,2465.0,2626.0,https://en.wikipedia.org/wiki/Zonuz,https://fa.wikipedia.org/wiki/%D8%B2%D9%86%D9%...,https://geohack.toolforge.org/geohack.php?lang...
1255,Zurabad,زرآباد,آذربایجان غربی,خوی,صفائیه,38.802808,44.585348,1718.0,NaN,1147.0,1239.0,"https://en.wikipedia.org/wiki/Zurabad,_West_Az...",https://fa.wikipedia.org/wiki/%D8%B2%D8%B1%D8%...,https://geohack.toolforge.org/geohack.php?lang...

In [32]:
typo_char = pd.read_csv('../data/typo_char.csv')
typo_char

   EN FA
0   a  ش
1   b  ذ
2   c  ز
3   d  ی
4   e  ث
5   f  ب
6   g  ل
7   h  ا
8   i  ه
9   j  ت
10  k  ن
11  l  م
12  m  ئ
13  n  د
14  o  خ
15  p  ح
16  q  ض
17  r  ق
18  s  س
19  t  ف
20  u  ع
21  v  ر
22  w  ص
23  x  ط
24  y  غ
25  z  ظ
26  ,  و
27  \  پ
28  C  ژ
29  H  آ
30  X  ي
31  ;  ک
32  [  ج
33  ]  چ
34  '  گ

<h2 align=right style="line-height:200%;font-family:vazir;color:#0099cc">
<font face="vazirmatn" color="#0099cc">
پیش‌پردازش و مهندسی ویژگی
</font>
</h2>

<p dir=rtl style="direction: rtl; text-align: justify; line-height:200%; font-family:vazir; font-size:medium">
<font face="vazirmatn" size=3>
    در این تمرین می‌توانید هر بلایی که می‌خواهید به سر داده‌ها بیاورید 😁 البته ممکن است با توجه به روشی که جهت حل مسئله انتخاب می‌کنید پیش‌پردازش‌های مورد نیاز شما نیز تفاوت کند.
</font>
</p>

In [33]:
data.isnull().sum()

ServiceType     0
TypedStrings    0
AcceptString    0
dtype: int64

In [34]:
data = data[data['ServiceType'].isin(['bus', 'taxi'])].copy()

In [35]:
en_to_fa_map = dict(zip(typo_char['EN'], typo_char['FA']))

def fix_keyboard(text):
    """Translates English characters to Persian layout."""
    if pd.isna(text): 
        return text
    return ''.join([en_to_fa_map.get(char, char) for char in str(text)])

exploded = data.explode('TypedStrings')

exploded = exploded[exploded['TypedStrings'] != '']
exploded = exploded.dropna(subset=['TypedStrings', 'AcceptString'])

freq_map = exploded.groupby(['TypedStrings', 'AcceptString']).size().reset_index(name='Count')

freq_map = freq_map.sort_values(by=['TypedStrings', 'Count'], ascending=[True, False])

history_dict = freq_map.groupby('TypedStrings')['AcceptString'].apply(list).to_dict()

In [36]:
all_cities = iran_cities['City FA'].dropna().unique()

top_overall_cities = data['AcceptString'].value_counts().head(10).index.tolist()

<h2 align=right style="line-height:200%;font-family:vazir;color:#0099cc">
<font face="vazirmatn" color="#0099cc">
مدل‌سازی
</font>
</h2>

<p dir=rtl style="direction: rtl; text-align: justify; line-height:200%; font-family:vazir; font-size:medium">
<font face="vazirmatn" size=3>
    برای حل این مسئله می‌توانید از هر روشی که به ذهن‌تان می‌رسد کمک بگیرید. توجه داشته باشید که در این تمرین با یک مسئله‌ی واقعی و صنعتی سر و کار داریم، در نتیجه ممکن است برخلاف تمرین‌های رایج کالج یک راه‌حل استاندارد یا به اصطلاح سرراست برای آن وجود نداشته باشد. حتی ممکن است الگوریتم‌های یادگیری ماشین برای این مسئله به اندازه‌ی راه‌حل‌های قاعده‌ای (rule-based) یا احتمالاتی مفید واقع نشود. همچنین می‌توانید چندین روش مختلف را با همدیگر ترکیب کنید. خلاصه که ریش (🧔) و قیچی (✂️) دست شماست! هر ایده و خلاقیتی که به ذهن‌تان می‌رسد را پیاده‌سازی و آزمایش کنید.
</font>
</p>

<p dir=rtl style="direction: rtl; text-align: justify; line-height:200%; font-family:vazir; font-size:medium">
<font face="vazirmatn" size=3>
    چندین مثال از نمونه‌های آزمون و پیشنهادهای معقول برای آن‌ها در زیر آورده شده تا به ایده‌پردازی شما کمک کند. توجه داشته باشید در صورتی‌که پیشنهاد چندان مشابهی وجود نداشته باشد می‌توانیم از پرتکرارترین یا محتمل‌ترین برچسب‌ها استفاده می‌کنیم. یعنی در مثال زیر مشاهده می‌کنید که هرجا انتخاب بهتری نداشته‌ایم ابتدا «تهران» و سپس باقی شهرها را قرار داده‌ایم.
</font>
</p>

<center>
<div dir=rtl style="direction: rtl;line-height:200%;font-family:vazir;font-size:medium">
<font face="vazirmatn" size=3>
    
|Suggestion4|Suggestion3|Suggestion2|Suggestion1|Suggestion0|متن تایپ‌شده|
|:------:|:---:|:---:|:---:|:---:|:---:|
| شیراز | اصفهان | کلاله | تهران - پایانه جنوب | تهران | تهد |
| قم | قایمیه | قاینات | قائن | قائم شهر | قا |
| اصفهان | تهران | خوی | بویین ومیاندشت | بویراحمد | بوی |
| شیراز | اصفهان | تهران | یزد - کمربندی | یزد | dcn |
| شیراز | اصفهان | تهران | ماهشهر | اهواز | بندر ماهش |
| تنکابن | تهران - پایانه غرب | تهران - پایانه جنوب | تبریز | تهران | ت |
    
</font>
</div>
</center>

In [37]:
def predict_suggestions(query):
    suggestions = []
    
    fixed_query = fix_keyboard(str(query).strip())
    
    if fixed_query in history_dict:
        for city in history_dict[fixed_query]:
            if city not in suggestions:
                suggestions.append(city)
            if len(suggestions) == 5:
                return suggestions  # Stop once we hit 5
                
    if len(suggestions) < 5 and len(fixed_query) > 0:
        for city in all_cities:
            if str(city).startswith(fixed_query):
                if city not in suggestions:
                    suggestions.append(city)
                if len(suggestions) == 5:
                    return suggestions
                    
    for city in top_overall_cities:
        if city not in suggestions:
            suggestions.append(city)
        if len(suggestions) == 5:
            return suggestions
            
    return suggestions

<h2 align=right style="line-height:200%;font-family:vazir;color:#0099cc">
<font face="vazirmatn" color="#0099cc">
معیار ارزیابی
</font>
</h2>

<p dir=rtl style="direction: rtl; text-align: justify; line-height:200%; font-family:vazir; font-size:medium">
<font face="vazirmatn" size=3>
    از آنجا که در این مسئله پاسخ حقیقی‌ای وجود ندارد خروجی‌های مدل شما با پیشنهادهای خروجی راه‌حل ما مقایسه می‌شود تا منطقی بودن پاسخ شما تا حد مناسبی سنجیده شود. برای مقایسه‌ی پیشنهادها به ازای هر نمونه‌ی آزمون از معیار شباهتی به نام Rank-biased Overlap یا به اختصار RBO استفاده می‌شود. به ازای هر نمونه مقدار RBO محاسبه شده و در نهایت از تمام مقادیر تولید شده میانگین گرفته خواهد شد.
</font>
</p>

<p dir=rtl style="direction: rtl; text-align: justify; line-height:200%; font-family:vazir; font-size:medium">
<font face="vazirmatn" size=3>
    برای محاسبه‌ی مقدار RBO بین دو لیست از آیتم‌ها از تابع <code>RankingSimilarity</code> موجود در کتابخانه‌ی <a href="https://github.com/changyaochen/rbo">rbo</a> استفاده خواهد شد.
</font>
</p>

In [38]:
# from rbo import RankingSimilarity
# act = ['A', 'B', 'C']
# pred = ['B', 'A', 'D']
# rbo = RankingSimilarity(act, pred).rbo()
# print(rbo)

#i really hate installing new libraries so i will not use this code and trust god to have a good model

<p dir=rtl style="direction: rtl; text-align: justify; line-height:200%; font-family:vazir; font-size:medium">
<font color="red"><b color='red'>توجه:</b></font>
<font face="vazirmatn" size=3>
 جهت کسب امتیاز کامل نیاز است تا پاسخ شما حداقل امتیاز <code>30</code> را با توجه به معیار معرفی‌شده کسب نماید.
</font>
</p>

<h2 align=right style="line-height:200%;font-family:vazir;color:#0099cc">
<font face="vazirmatn" color="#0099cc">
 پیش‌بینی برای داده تست و خروجی
</font>
</h2>

<p dir=rtl style="direction: rtl; text-align: justify; line-height:200%; font-family:vazir; font-size:medium">
<font face="vazirmatn" size=3>
    به ازای هر نمونه‌ی آزمون نیاز است ۵ شهر (مقادیر برچسب یعنی ستون <code>AcceptString</code>) را به‌ترتیب اولویت پیش‌بینی کرده و همانند جدول و کد نمونه‌ی زیر در دیتافریمی به نام <code>submission</code> ذخیره کنید. توجه داشته باشید که در میان ۵ پیش‌بینی خود <span style="color:red">نباید</span> عنصر تکراری‌ای وجود داشته باشد.
</font>
</p>

<center>
<div dir=rtl style="direction: rtl;line-height:200%;font-family:vazir;font-size:medium">
<font face="vazirmatn" size=3>
    
|ستون|توضیحات|
|:------:|:---:|
|<code>Suggestion0</code>|پیش‌بینی نخست (بیشترین اولویت)|
|<code>Suggestion1</code>|پیش‌بینی دوم|
|<code>Suggestion2</code>|پیش‌بینی سوم|
|<code>Suggestion3</code>|پیش‌بینی چهارم|
|<code>Suggestion4</code>|پیش‌بینی پنجم (کمترین اولویت)|
    
</font>
</div>
</center>

In [39]:
predictions = test_data['Typed'].apply(predict_suggestions)

submission = pd.DataFrame(predictions.tolist(), columns=[
    'Suggestion0', 'Suggestion1', 'Suggestion2', 'Suggestion3', 'Suggestion4'
])

submission

    Suggestion0          Suggestion1 Suggestion2 Suggestion3 Suggestion4
0         تهران  تهران - پایانه جنوب       کلاله      اصفهان        مشهد
1        نهاوند                تهران      اصفهان        مشهد       شیراز
2          ساوه                 تفرش       تهران          قم      اصفهان
3         یاسوج                شیراز       بوشهر      اصفهان        بابل
4    بندر انزلی           بندر ترکمن      عسلویه       تهران      اصفهان
..          ...                  ...         ...         ...         ...
514         یزد                تهران      اصفهان      ابرکوه    فولادشهر
515         کرج                کرمان    کرمانشاه       تهران       سنندج
516       بوکان                 بانه      ارومیه       تبریز         سقز
517       داراب              خوانسار       شیراز      اصفهان         یزد
518      آبادان                شیراز       تهران      اصفهان        مشهد

[519 rows x 5 columns]

<h2 align=right style="line-height:200%;font-family:vazir;color:#0099cc">
<font face="vazirmatn" color="#0099cc">
<b>سلول جواب‌ساز</b>
</font>
</h2>

<p dir=rtl style="direction: rtl; text-align: justify; line-height:200%; font-family:vazir; font-size:medium">
<font face="vazirmatn" size=3>
    برای ساخته‌شدن فایل <code>result.zip</code> سلول زیر را اجرا کنید. توجه داشته باشید که پیش از اجرای سلول زیر تغییرات اعمال شده در نت‌بوک را ذخیره کرده باشید (<code>ctrl+s</code>) تا در صورت نیاز به پشتیبانی امکان بررسی کد شما وجود داشته باشد.
</font>
</p>

In [40]:
import zipfile
import joblib
import os

if not os.path.exists(os.path.join(os.getcwd(), 'auto_suggest.ipynb')):
    %notebook -e text_categorization.ipynb

def compress(file_names):
    print("File Paths:")
    print(file_names)
    compression = zipfile.ZIP_DEFLATED
    with zipfile.ZipFile("result.zip", mode="w") as zf:
        for file_name in file_names:
            zf.write('./' + file_name, file_name, compress_type=compression)

submission.to_csv('submission.csv', index=False)
file_names = ['auto_suggest.ipynb', 'submission.csv']
compress(file_names)

File Paths:
['auto_suggest.ipynb', 'submission.csv']

<h4 align=right style="line-height:200%;font-family:vazir;color:#0099cc">
<font face="vazirmatn" color="#0099cc">
<b>راهنمایی</b>
</font>
</h4>

<p dir=rtl style="direction: rtl; text-align: justify; line-height:200%; font-family:vazir; font-size:medium">
<font face="vazirmatn" size=3>
    ۱. در پیش‌بینی‌ تولید شده اولویت با شهرهایی است که دقیقاً با آن‌چه که کاربر تایپ کرده شروع شوند.
    <br>
    ۲. خود را به استفاده از تنها یک روش استاندارد محدود نکنید و از روش‌های ترکیبی و خلاقانه‌ای که به ذهن‌تان می‌رسد کمک بگیرید.
</font>
</p>